### PR TITLE
Update the global configuration location and fix 2 typos in readme

### PR DESCRIPTION
**Pull request by zhenglaizhang**
2 refinements on README.md: 
* Remove the invalid path segment '/project' from the global configuration location: `home/project => home`.
* And fix 2 typos in it.

### CODE REVIEW

**Comment by piotrmurach** [comment]
Thanks :heart: 

Unfortunately I have bad news, this library hasn't been maintained for couple years and is terribly out of sync(some things may work but I would expect some apis to be broken). I'm working on bringing it up to speed with latest api. If you have time and want to take a look at implementing any apis calls that would be sweet.

**Comment by zhenglaizhang** [comment]
I think the lib is very useful and convenient(👍 ) for me (and others)  to easily access github from cli. 
And currently I am so interested in Ruby related development, so I am sure I will be glad that I will take a chance to be involved in the lib development.

Is there any roadmap or the api list that we need to update or implement? I would take some as the starting point to contribute to that. 

I just met with the lib yesterday and didn't try many commands, so I will take a full view and understanding of the lib this week, and I will try to find something broken to fix that.

**Comment by piotrmurach** [comment]
Sounds fantastic!

The library relies on the [github_api gem](https://github.com/piotrmurach/github) which has majority of official GitHub api implemented [see](https://github.com/piotrmurach/github/tree/master/lib/github_api/client). I will update this library to use `v0.14.0` that was released few days ago.

As a way of cross referencing I use the [official GitHub api docs](https://developer.github.com/v3/) which will show you possible parameters, response types etc...

All the current commands can be found [here](https://github.com/piotrmurach/github_cli/tree/master/lib/github_cli/commands). And the best one to start with would be probably the search command as this is broken for people reporting problems on the issue tracker [see](https://github.com/piotrmurach/github_cli/issues/18)

Everything that is current is in the master and I will not step on your tones changing api as I have quite a lot of things to change in the library regarding all the plumbing. 

I will add chat client tomorrow so that you can catch me there as well in case you have any questions.

**Comment by zhenglaizhang** [comment]
Great, thanks for the useful info. I will take time to go through the related links when I'm off work today and reach you back if I have questions then.

I will definitely take the search issue and try to fix this this weekend.

**Pull request merged**
